name: Deploy to EC2 via OIDC

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy JAR to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload JAR to S3
        run: |
          aws s3 cp ./build/libs/air-quality-platform-0.0.1-SNAPSHOT.jar s3://${{ secrets.S3_BUCKET_NAME }}/

      - name: Connect to EC2 and deploy JAR
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/deploy
            aws s3 cp s3://${{ secrets.S3_BUCKET_NAME }}/air-quality-platform-0.0.1-SNAPSHOT.jar .
            chmod +x deploy.sh
            ./deploy.sh
