name: Deploy to EC2 with OIDC and S3

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::916662722416:role/GitHubActionsEC2DeployRole
          aws-region: ap-northeast-2

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build JAR with Gradle (Skip Test)
        run: ./gradlew build -x test

      - name: Upload JAR to S3
        run: aws s3 cp ./build/libs/air-quality-platform-0.0.1-SNAPSHOT.jar s3://capstonedesign-deploy-bucket/

      - name: Connect to EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@18.191.176.79 << 'EOF'
          aws s3 cp s3://capstonedesign-deploy-bucket/air-quality-platform-0.0.1-SNAPSHOT.jar ~/deploy/
          cd ~/deploy
          chmod +x deploy.sh
          ./deploy.sh
          EOF
