name: Deploy to EC2

on:
  push:
    branches: [ "main" ]  # 또는 사용하는 브랜치 이름

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/spring-key.pem
          chmod 600 ~/.ssh/spring-key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/spring-key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/deploy
            git pull origin main
            chmod +x deploy.sh
            ./deploy.sh
          EOF
